return function ()
	return {
		name = {"tiergen-config.science-pack-galore"},
		ultimate_science = lib.item("space-science-pack"),
		all_sciences = lib.items{
			"automation-science-pack",
			"logistic-science-pack",
			"military-science-pack",
			"chemical-science-pack",
			"production-science-pack",
			"utility-science-pack",
			"space-science-pack",
			"sem:spg_science-pack-1",
			"sem:spg_science-pack-2",
			"sem:spg_science-pack-3",
			"sem:spg_science-pack-4",
			"sem:spg_science-pack-5",
			"sem:spg_science-pack-6",
			"sem:spg_science-pack-7",
			"sem:spg_science-pack-8",
			"sem:spg_science-pack-9",
			"sem:spg_science-pack-10",
			"sem:spg_science-pack-11",
			"sem:spg_science-pack-12",
			"sem:spg_science-pack-13",
			"sem:spg_science-pack-14",
			"sem:spg_science-pack-15",
			"sem:spg_science-pack-16",
			"sem:spg_science-pack-17",
			"sem:spg_science-pack-18",
			"sem:spg_science-pack-19",
			"sem:spg_science-pack-20",
			"sem:spg_science-pack-21",
			"sem:spg_science-pack-22",
			"sem:spg_science-pack-23",
			"sem:spg_science-pack-24",
			"sem:spg_science-pack-25",
			"sem:spg_science-pack-26",
			"sem:spg_science-pack-27",
			"sem:spg_science-pack-28",
			"sem:spg_science-pack-29",
			"sem:spg_science-pack-30",
			"sem:spg_science-pack-31",
			"sem:spg_science-pack-32",
			"sem:spg_science-pack-33",
			"sem:spg_science-pack-34",
			"sem:spg_science-pack-35",
			"sem:spg_science-pack-36",
		},
		base_items = {},
		ignored_recipes = {},
	}
end